---
# argument spec file for splunk.itsi.itsi_read_episodes

argument_specs:
  main:
    short_description: Role description.
    options:
      my_variable:
        type: str
        description: A simple string argument for demonstration.
        default: "default_value"
