---
# tasks file for splunk.itsi.itsi_read_episodes

# task example for debugging a value
- name: Debug the value of my_variable
  ansible.builtin.debug:
    msg: "The value of my_variable is {{ my_variable }}"
